version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directories: [/app/api, /app/worker]
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directories: [/app/api, /app/worker]
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directories: [/infra/bootstrap, /infra/environment]
    schedule:
      interval: weekly
